version: '3.8'
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  parsers:
    container_name: parsers
    build:
      context: ./parsers
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - mynetwork

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "5173:5173"
      - "3000:3000"
    depends_on:
      - parsers
    networks:
      - mynetwork

networks:
  mynetwork:
