version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  parsers:
    build:
      context: ./parsers
    env_file:
      - .env
    volumes:
      - ./parsers:/app
    depends_on:
      - redis
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
      - "3000:3000"
    depends_on:
      - parsers
    networks:
      - mynetwork

networks:
  mynetwork:
